In [1]:
import numpy as np

In [4]:
A = np.array([[-1, 0, 0],[0,2,0],[0,0,2]])
B = np.array([[1, 1, 0],[2,1,1],[3,0,1]])
print(np.dot(np.dot(B,A),np.linalg.inv(B)))

[[ 0.5  1.5 -1.5]
 [-3.   5.  -3. ]
 [-4.5  4.5 -2.5]]


In [3]:
# question 5b
A = np.array([[1,0,2],[-1,1,3],[0,0,1]])
print(np.linalg.qr(A))

(array([[-0.70710678,  0.70710678,  0.        ],
       [ 0.70710678,  0.70710678,  0.        ],
       [-0.        , -0.        ,  1.        ]]), array([[-1.41421356,  0.70710678,  0.70710678],
       [ 0.        ,  0.70710678,  3.53553391],
       [ 0.        ,  0.        ,  1.        ]]))


# Question 6

In [28]:
A = np.array([[0.9, 0.04, 0.1],[0.06,0.95,0],[0.04,0.01,0.9]])

In [29]:
a,b = np.linalg.eig(A)

In [30]:
print(a)

[1.   0.83 0.92]


In [31]:
print(b)

[[-0.60741191 -0.81649658  0.40824829]
 [-0.7288943   0.40824829 -0.81649658]
 [-0.31585419  0.40824829  0.40824829]]


In [24]:
l = np.array([[a[0],0,0],[0,a[1],0],[0,0,a[2]]])

In [32]:
print(l)
np.dot(np.dot(b,l),np.linalg.inv(b))

[[1.   0.   0.  ]
 [0.   0.92 0.  ]
 [0.   0.   0.83]]


array([[ 0.94191176,  0.05191176, -0.00808824],
       [ 0.05029412,  0.91029412,  0.11029412],
       [ 0.00779412,  0.03779412,  0.89779412]])

In [33]:
np.dot(np.dot(b,l**100000000),np.linalg.inv(b))

array([[0.36764708, 0.36764708, 0.36764708],
       [0.44117649, 0.44117649, 0.44117649],
       [0.19117648, 0.19117648, 0.19117648]])

In [34]:
linf = np.array([[1,0,0],[0,0,0],[0,0,0]])
np.dot(np.dot(b,linf),np.linalg.inv(b))

array([[0.36764706, 0.36764706, 0.36764706],
       [0.44117647, 0.44117647, 0.44117647],
       [0.19117647, 0.19117647, 0.19117647]])

In [5]:
# question 10
A = np.array([[1,2,1],[6,-1,0],[-1,-2,-1]])
print(np.linalg.eig(A))

(array([-4.00000000e+00,  3.00000000e+00,  1.71642331e-16]), array([[ 0.40824829, -0.48507125, -0.0696733 ],
       [-0.81649658, -0.72760688, -0.41803981],
       [-0.40824829,  0.48507125,  0.90575292]]))


In [8]:
P = np.array([[1,1,2],[6,-2,3],[-13,-1,-2]])
print(P)
print(np.linalg.inv(P))
print(np.linalg.det(P))
C = (np.linalg.det(P)*np.linalg.inv(P))
print(C)

[[  1   1   2]
 [  6  -2   3]
 [-13  -1  -2]]
[[-0.08333333 -0.         -0.08333333]
 [ 0.32142857 -0.28571429 -0.10714286]
 [ 0.38095238  0.14285714  0.0952381 ]]
-83.99999999999999
[[  7.   0.   7.]
 [-27.  24.   9.]
 [-32. -12.  -8.]]


In [5]:
# question 1
A = np.array([[3,-4,-1],[8,9,2],[0,7,6]])
print(np.linalg.det(A))

255.99999999999972


In [6]:
A = np.array([[1,-1,0],[1,2,2],[3,0,2]])
print(np.linalg.det(A))

-6.66133814775094e-16
